provider:
  name: faas
  gateway: http://localhost:8080

functions:
  normalisecolor:
    lang: Dockerfile
    handler: ./normalisecolor
    image: alexellis2/normalisecolor:0.2
  colorization:
    lang: Dockerfile
    handler: ./colorise
    image: alexellis2/openfaas-colorization:0.2.2
    environment:
      read_timeout: 60
      write_timeout: 60
      write_debug: true
      minio_authority: minio.openfaas-fn:9000
      gateway_url: http://gateway.openfaas:8080
    environment_file:
      - credentials.yaml
  tweetpic:
    lang: Dockerfile
    handler: ./tweetpic
    image: alexellis2/openfaas-tweetpic:0.2.2
    environment:
      read_timeout: 60
      write_timeout: 60
      minio_authority: minio.openfaas-fn:9000
      gateway_url: http://gateway.openfaas:8080
    environment_file:
      - credentials.yaml
