---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    flux.weave.works/locked: "true"
  name: alertmanager
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.9.1
        imagePullPolicy: Always
        command:
          - alertmanager
          - -config.file=/alertmanager.yml
          - -storage.path=/alertmanager
        ports:
        - containerPort: 9093
          protocol: TCP
        resources:
          limits:
            memory: 128Mi
        volumeMounts:
        - mountPath: /alertmanager.yml
          name: alertmanager-config
          subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
                mode: 0644

