---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: gateway
  namespace: openfaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: functions/gateway:0.6.12
        imagePullPolicy: Always
        env:
        - name: functions_provider_url
          value: "http://faas-netesd.openfaas:8080/"
        - name: faas_nats_address
          value: "nats.openfaas"
        - name: faas_nats_port
          value: "4222"
        - name: write_timeout
          value: "60"
        - name: read_timeout
          value: "60"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 1024Mi
