---
apiVersion: v1
kind: Service
metadata:
  name: mailbox
  namespace: openfaas-fn
  labels:
    app: mailbox
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: mailbox


