---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: openfaas-fn
  labels:
    app: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: minio

