---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: minio
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2017-11-22T19-55-46Z
        command: ["minio"]
        args: ["server", "/storage"]
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-auth
              key: secret
        ports:
        - containerPort: 9000
          hostPort: 9000
        volumeMounts:
        - name: minio-pv
          mountPath: "/storage"
      volumes:
        - name: minio-pv
          gcePersistentDisk:
            pdName: minio-disk
            fsType: ext4
